apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 192.168.10.21
    path: /srv/nfs/kubernetes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  minReadySeconds: 5
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx-container
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-container
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc