apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-cleanup
  namespace: devel
  annotations: 
    description: "Job to clean up old nginx logs"
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        type: log-cleanup
      namespace: devel
    spec:
      containers:
        - name: nginx-cleanup
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          command: ['/bin/bash', '-c']
          args: ['rm -f /var/log/nginx/*.log']
      restartPolicy: OnFailure