apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
  namespace: default
  labels:
    type: nodeAffinity
  annotations:
    Description: "This is a Pod that tests node affinity."
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: wokerlaod
                operator: In
                values:
                  - woker-1
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80