apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity
  namespace: default
  labels:
    podType: podAntiAffinity
  annotations:
    Description: "Test podAntiAffinity Pod"
spec:
  containers:
    - name: pod-anti-affinity
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              type: podAffinity
          topologyKey: "kubernetes.io/hostname"