apiVersion: v1
kind: Pod
metadata:
  name: podaffinity
  namespace: default
  labels:
    schedulerType: podAffinity
    namespace: kube-system
  annotations:
    Description: "This is a podAffinity test Pod"
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: nginx
            topologyKey: "kubernetes.io/hostname"
  containers:
    - name: pod-affinity
      image: nginx