apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  namespace: default
  labels:
    type: podAffinity
  annotations:
    Description: "This is a Pod that tests pod affinity."
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          podAffinityTerm:
            labelSelector:
              matchLabels:
                type: nodeAffinity
            topologyKey: "kubernetes.io/hostname"
  containers:
    - name: pod-affinity
      image: nginx:latest
      ports:
        - containerPort: 80