apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: devel
  labels:
    app: service
  spec:
    type: NodePort
    clusterIP: 10.96.0.2
    ports:
      - name: nginx-port
        port: 80
        targetPort: 80
        nodePort: 8080
    selector:
      app: nginx
      env: devel