apiVersion: v1
kind: Pod
metadata:
  name: probe-example
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-containers
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    workingDir: /usr/share/nginx/html
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      httpGet:
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    livenessProbe:
      httpGet:
        port: 80
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 2
      failureThreshold: 3
      successThreshold: 1