apiVersion: v1
kind: Pod
metadata:
  name: tolerations-pod
  labels:
    app: nginx
  annotations:
    kubernetes.io/description: "This is a tolerations pod example"
spec:
  activeDeadlineSeconds: 360
  containers:
  - name: nginx-containers
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    workingDir: /usr/share/nginx/html
    ports:
    - containerPort: 8080
      protocol: TCP
  nodeSelector:
    kubernetes.io/hostname: kube-master
  tolerations:
  - key:  node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule