apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    version: 1.14
    environment: development
  annotations: 
    description: "This is a simple Nginx pod for demonstration purposes."
    createdBy: "alex fan"
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 8080
  